agent: "C51DQN"
vectorize: "Dummy_Atari"
env_name: "Atari"
env_id: "ALE/Breakout-v5"
env_seed: 1
obs_type: "grayscale"  # choice for Atari env: ram, rgb, grayscale
img_size: [84, 84]  # default is 210 x 160 in gym[Atari]
num_stack: 4  # frame stack trick
frame_skip: 4  # frame skip trick
noop_max: 30  # Do no-op action for a number of steps in [1, noop_max].
learner: "C51_Learner"
policy: "C51_Q_network"
representation: "Basic_CNN"
runner: "DRL"

# the following three arguments are for "Basic_CNN" representation.
filters: [32, 64, 64]
kernels: [8, 4, 3]
strides: [4, 2, 1]

q_hidden_size: [512, ]
activation: "relu"

seed: 1069
parallels: 5
buffer_size: 1000000  # 1M
batch_size: 32
learning_rate: 0.00025
gamma: 0.99
v_min: -10
v_max: 10
atom_num: 51

start_greedy: 1.0
end_greedy: 0.01
decay_step_greedy: 1000000  # 1M
sync_frequency: 10000
training_frequency: 4
running_steps: 10000000  # 10M
start_training: 50000  # 50K

use_grad_clip: False  # gradient normalization
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 500000
test_episode: 3
log_dir: "./logs/c51/"
model_dir: "./models/c51/"
