agent: "Duel_DQN"
vectorize: "Dummy_Atari"
env_name: "Atari"
env_id: "ALE/Breakout-v5"
env_seed: 1
obs_type: "grayscale"  # choice for Atari env: ram, rgb, grayscale
img_size: [84, 84]  # default is 210 x 160 in gym[Atari]
num_stack: 4  # frame stack trick
frame_skip: 4  # frame skip trick
noop_max: 30  # Do no-op action for a number of steps in [1, noop_max].
policy: "Duel_Q_network"
representation: "Basic_CNN"
learner: "DuelDQN_Learner"
runner: "DRL"

# the following three arguments are for "Basic_CNN" representation.
filters: [32, 64, 64]
kernels: [8, 4, 3]
strides: [4, 2, 1]

q_hidden_size: [512, ]
activation: "relu"

seed: 1069
parallels: 5
buffer_size: 1000000  # 1M
batch_size: 32
learning_rate: 0.0000625
gamma: 0.99

start_greedy: 1.0
end_greedy: 0.1
decay_step_greedy: 1000000  # 1M
sync_frequency: 10000
training_frequency: 4
running_steps: 10000000  # 10M
start_training: 50000  # 50K

use_grad_clip: True  # gradient clipping
grad_clip_norm: 10
use_actions_mask: False
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
save_model_frequency: 500000
test_episode: 1
log_dir: "./logs/dueldqn/"
model_dir: "./models/dueldqn/"
